meta_league_api:
    type: annotation
    prefix:   /api
    resource: "@MetaLeagueAPIBundle/Controller"

meta_league_fantasy:
    resource: "@MetaLeagueFantasyBundle/Controller"
    prefix:   /
    type: annotation

meta_league_site:
    resource: "@MetaLeagueSiteBundle/Controller"
    prefix:   /
    type: annotation

#FOSUser Stuff
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
        
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc    