parameters:
#    meta_league_site.example.class: MetaLeague\SiteBundle\Example

services:
#    meta_league_site.example:
#        class: %meta_league_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
