parameters:
#    meta_league_site.example.class: MetaLeague\SiteBundle\Example

services:
    meta_league_site.example:
        class: MetaLeague\SiteBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: meta_league_registration }