<?php

namespace MetaLeague\FantasyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GamePositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamePositionRepository extends EntityRepository
{
}
