<?php

namespace MetaLeague\FantasyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProGameActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProGameActionRepository extends EntityRepository
{
}
