<?php

namespace MetaLeague\FantasyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProTeamRepository extends EntityRepository
{
}
